FROM golang:1.26-bullseye

# 设置工作目录
WORKDIR /app

# 安装 GoCV 所需依赖
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    make \
    cmake \
    pkg-config \
    libopencv-dev && \
    rm -rf /var/lib/apt/lists/*

# 启用 CGO
ENV CGO_ENABLED=1

# 复制项目文件
COPY . .

# 下载 Go 依赖
RUN go mod download

# 构建项目
RUN go build -o scanrectifier .

# 运行
CMD ["./scanrectifier"]
